### ISSUE TITLE
Usage Direction | Config file mising

### ISSUE THREAD

**Issue by rabimba** [NewEconomyMovement/nem-slack-telegram#4]
@patmast3r I was trying to run your code (I hope it is allowed? I didn't find any licnese that prohibits it...) and it seems it also wants to find a config file. Is that a requirement? And what shoould be in it? Also where does the telegram and slack API keys go?

**Comment by patmast3r** [comment]
@rabimba Hey man, sorry for answering so late. I honestly didn't think anyone was gonna use this since it's tailored pretty specificly to our usage. Anyway it should work for you as well and I'm happy to help you set it up. 

Yes, you need a config file which is where the API-Keys are stored. You can skip that by simply putting the API keys int he places where it reads from them but I suggest to use it since it simplifies the git-workflow. 

I'll push a template config file for you as soon as I get around to it.

**Comment by rabimba** [comment]
Thanks. Also I was wondering can you just tell me the steps I need to do ro make it work?
Apart from just putting in the API key?

**Comment by patmast3r** [comment]
@rabimba I've put some info in the readme. See if you can get it running with that. If not I'll edit it to answer any of your further questions.

**Comment by rabimba** [comment]
Thanks!
I get something like this when I run it and type something in slack. 
![image](https://cloud.githubusercontent.com/assets/776740/14443213/635d721e-0003-11e6-9c55-facda95008ef.png)

I don't get any activity at all when i type in telegram.

Couple of queries to see if I am doing everything right. The telegram api key consists of "ap_id:apphash" and the telegram group in the matching part should be just like 'my telegram group' instead of the -898989 things that was in bridge.py. Right?

**Comment by rabimba** [comment]
So my latest status.
Telegram -> Slack working fine enough.

But when I have anyone posting anything in Slack I get this 

![image](https://cloud.githubusercontent.com/assets/776740/14546765/444dcd3a-026d-11e6-830b-dcf415bcb137.png)

**Comment by patmast3r** [comment]
> the matching part should be just like 'my telegram group' instead of the -898989 things that was in bridge.py. Right?

Nope. The group-ids do looke like that i.e. similar to -898989. I'm not using telegram myself so I'm not sure about the terminology of group vs. channel on telegram.

**Comment by patmast3r** [comment]
I'll close this issue and we'll track it further in the issue dedicated to this very problem.
